FROM node:latest as builder

WORKDIR /app

COPY . /app

RUN npm install -g yarn && \
    yarn && \
    yarn build

FROM nginx:alpine as runner

WORKDIR /srv

COPY builder:/app/dist /srv

COPY ./deploy/nginx/nginx.conf /etc/nginx/nginx.conf
